#!/usr/bin/env bash
# does a lot of things

finish()
{
	rm /var/run/myscript.pid
	exit
}

echo $$ > /var/run/myscript.pid
while true
do
	echo To infinity and beyond
	sleep 2
	trap 'echo I hate the kill command' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	trap 'finish' SIGTERM
	trap 'finish' SIGQUITgit
done
