#!/usr/bin/env bash
#use of if elif and ese with while

i=1
while ((i <= 10))
do
	if ((i == 4))
	then
		echo bad luck
	elif ((i == 8))
	then
		echo good luck
	else
		echo Best School
	fi
	((i++))
done
