#!/usr/bin/env bash
# change hosts contents

if [ -e /etc/hosts ]
then
	sudo cp /etc/hosts /etc/hosts.old
	if grep -q '^.*localhost$' /etc/hosts;
	then
		sudo sed -i 's/^.*localhost$/127.0.0.2	localhost/' /etc/hosts
	else
		echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
	fi
	if grep -q '^.*facebook.com$' /etc/hosts
	then
		sudo sed -i 's/^.*facebook.com$/8.8.8.8	facebook.com/' /etc/hosts
	else
		sudo echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts > /dev/null
	fi
else
	sudo echo "127.0.0.2	localhost" | sudo tee /etc/hosts > /dev/null
	sudo echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
