#!/usr/bin/env bash
# change hosts contents

if [ -e /etc/hosts ]
then
	sudo cp /etc/hosts /etc/hosts.old
	if grep -q '^.*localhost$' /etc/hosts;
	then
		sudo sed -i 's/^.*localhost$/127.0.0.2	localhost/' /etc/hosts
	else
		sudo echo "127.0.0.2	localhost" >> /etc/hosts
	fi
	if grep -q '^.*facebook.com$' /etc/hosts
	then
		sudo sed -i 's/^.*facebook.com$/8.8.8.8	facebook.com/'
	else
		sudo echo "8.8.8.8	facebook.com" >> /etc/hosts
	fi
else
	sudo echo "127.0.0.2	localhost" > /etc/hosts
	sudo echo "8.8.8.8	facebook.com" >> /etc/hosts
fi
